### ISSUE TITLE
Do not use Python strings like this! 

### ISSUE THREAD

**Issue by kamyar1979** [kavenegar/kavenegar-python#6]
https://github.com/kavenegar/kavenegar-python/blob/166701dd562f8b03d84d7ac89415a137455abba7/kavenegar.py#L38

**Comment by kamyar1979** [comment]
Too many + operators for immutable type! Use string format instead:
`url = 'https://{}/{}/{}/{}/{}.json'.format(self.host, self.version, self.apikey, action, method)`

**Comment by rezaxd** [comment]
Hello @kamyar1979 !
I created PR that fixed this.
hope u feel better, like me. :D

**Comment by kamyar1979** [comment]
Actually, the whole code and even API is bullshit! REST API must get Json/XMl/... not Form Data! Variable names obey none of naming conventions! (Variables with multiple words are not separated neither with letter case nor with _) The SDK code is very BAD! No OpenAPI! IT is really 'khosolati'!

**Comment by kamyar1979** [comment]
We do not use this piece of shit! Instead we created a Swagger and use some swagger invoker!

**Comment by rezaxd** [comment]
Sometime you don't have enough time for doing stuff by urself.
I agree with you that the API sucks.
But... IDK! :(((

**Comment by torkashvand** [comment]
please refactor this piece of shit! I prefer to write my own code! don't waste our time
